- name: scripts repo
  git:
    repo: git@github.com:adamchainz/chainz-scripts.git
    dest: ~/script
    update: false

- name: iTerm custom settings file
  osx_defaults:
    domain: com.googlecode.iterm2
    key: PrefsCustomFolder
    type: string
    value: "{{ ansible_env.PWD }}/roles/dihao_mac/files"

- name: Sublime Text 3 settings
  git:
    repo: git@github.com:ldihao/sublime_text_3_settings.git
    dest: '~/Library/Application Support/Sublime Text 3/Packages/User'

- name: Cowsay cowfile
  file:
    src: '{{ ansible_env.PWD }}/roles/dihao_mac/files/two-heads.cow'
    dest: /usr/local/Cellar/cowsay/3.04_1/share/cows/two-heads.cow
    state: link
